name: Build Android APK

on:
  push:
    branches:
      - main  # 你可以根据需要更改为其他分支
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          # cache: yarn

      - name: Install dependencies
        run: |
          yarn global add expo
          yarn global add eas-cli
          yarn

      - name: Build Android APK
        run: |
          npx expo prebuild
          cd android && ./gradlew assembleRelease


      - name: Upload APK
        uses: actions/upload-artifact@v4  # 使用最新版本
        with:
          name: android-apk
          path: ./android/app/build/outputs/apk/release/app-release.apk  # 根据你的项目结构调整路径
